// Get all blogs
GET {{host}}:{{port}}/Blogs

###

// Get second and third blog
GET {{host}}:{{port}}/Blogs?Skip=1&Take=2

###

// Creates a blog
POST {{host}}:{{port}}/Blogs
Content-Type: application/json

{
  "name": "New Blog",
  "description": "The description of the new blog"
}

### 

// Tries to creates an invalid blog
POST {{host}}:{{port}}/Blogs
Content-Type: application/json

{
  "name": null,
  "description": "Cannot create without a name"
}
