// Creates a blog
POST {{host}}:{{port}}/Blogs
Content-Type: application/json

{
  "name": "New Blog",
  "description": "The description of the new blog"
}

### Create an article
POST {{host}}:{{port}}/Articles
Content-Type: application/json

{
  "blogId": 8,
  "title": "New Article",
  "description": "The description of the new article"
}

###

// Get all articles
GET {{host}}:{{port}}/Articles

###


// Get a specific contributor
@id_to_get=1
GET {{host}}:{{port}}/Contributors/{{id_to_get}}

###

// Add a new contributor
POST {{host}}:{{port}}/Contributors
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "test@test.com",
  "phoneNumber": "1234567890"
}

###

// Update a contributor
@id_to_update=1
PUT {{host}}:{{port}}/Contributors/{{id_to_update}}
Content-Type: application/json

{
  "id": {{id_to_update}},
  "name": "ardalis2"
}

###

// Delete a contributor
@id_to_delete=1
DELETE {{host}}:{{port}}/Contributors/{{id_to_delete}}

